version: "3"
services:
  inline:
    image: doublehub/inline:latest
    # command: tail -f /etc/hosts
    restart: on-failure
    volumes:
      - $PWD:/final_screen
      - $PWD/config.json:/config.json
    shm_size: 2gb
    env_file:
      - .env
